Repository hms-dbmi/pic-sure-gic-institution-frontend, pull requests merged in 2024-01, with the labels that each got.

#37 [ALS-5510] Update JUnit
  ui/pom.xml
Labels: ignore-for-release

#39 [ALS-5056] Create UI for uploading data to S3
  ui/src/main/webapp/picsureui/requestSearch/requestSearch.hbs
  ui/src/main/webapp/picsureui/requestSearch/requestSearch.js
  ui/src/main/webapp/picsureui/requestSearch/requestSearchResult.hbs
  ui/src/main/webapp/picsureui/requestSearch/requestSearchResult.js
Labels: enhancement

#38 [ALS-5059] Create access rules for uploader
  custom-migrations/auth/V12__ADD_RULES.sql
Labels: enhancement

#40 Touchups
  ui/src/main/webapp/picsureui/requestSearch/dataStoreLocationHelp.hbs
  ui/src/main/webapp/picsureui/requestSearch/dataStoreLocationHelp.js
  ui/src/main/webapp/picsureui/requestSearch/requestSearch.hbs
  ui/src/main/webapp/picsureui/requestSearch/requestSearchResult.hbs
  ui/src/main/webapp/picsureui/requestSearch/requestSearchResult.js
  ui/src/main/webapp/picsureui/requestSearch/verifySendModal.hbs
  ui/src/main/webapp/picsureui/requestSearch/verifySendModal.js
Labels: enhancement

#42 Demo ahhhhh
  ui/src/main/webapp/picsureui/requestSearch/requestSearchResult.hbs
Labels: bug

#43 [ALS 4774] - Change "Lead PI" to "Requester"
  ui/src/main/webapp/picsureui/requestSearch/requestSearchResult.hbs
Labels: bug
